services:
  - type: web
    name: whatchardoing3-backend
    runtime: node
    buildCommand: "npm install --production"
    startCommand: node server.cjs
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: false 