services:
  - type: web
    name: whatchardoing3-backend
    env: node
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_FRONTEND_BUILD
        value: "true" 